#!/usr/bin/env python3
"""registry.py — THE PERSONAL DECISION LAYER: standing rules that kill context re-read.

WHY THIS EXISTS (Cockpit v2 spec, EPIC-1):
228 local sessions, 34.5B tokens, 62.7% of spend re-reading history — the single biggest line item
is re-deriving decisions that were already made once. A ticket, a fact, a chat: all of those are
scoped to ONE piece of work. What's missing is the layer above them — "how Chris works" — that
should be true in every repo, every session, without ever being restated.

WHERE THE LAW ACTUALLY LIVES, AND WHY THAT'S TWO DIRECTORIES NOT ONE:
Claude Code has a real, documented mechanism for this: `~/.claude/CLAUDE.md` and `~/.claude/rules/
*.md` load automatically into EVERY session in EVERY repo (confirmed against Claude Code's own
memory-loading docs before building this, not assumed) — that's what makes "an agent in the Mercato
repo applies a rule it was never told in-session" a real, testable outcome rather than a hope.

But that mechanism has no concept of "proposed" — anything Claude Code finds in `~/.claude/rules/`
is live, binding, loaded into context immediately. And the whole point of the promotion flywheel
(EPIC-1 T-1.4, per the operator's own explicit choice) is that a REPEATED correction becomes a
*proposal* a human reviews, never a rule that silently starts governing sessions on its own. So:

  ~/.claude/registry/<id>.md   — THE SOURCE OF TRUTH. Every entry, every status (proposed/law/
                                  rejected/retired), full provenance. This is what Cockpit's
                                  Registry surface reads and writes directly — "one source of
                                  truth, no copies," per the spec.
  ~/.claude/rules/hoodie-registry-<id>.md
                                — a GENERATED, disposable mirror containing ONLY status=law entries,
                                  regenerated by sync_rules_dir() after every mutation that could
                                  change which entries are law. This is the file Claude Code itself
                                  actually reads. Never hand-edit these; edit the registry entry and
                                  re-sync.

ONE FILE PER ENTRY, deliberately not a shared index — same reasoning agent_tickets.py's storage
redesign already established (avoids the shared-mutable-file collision class), doubly true here
since this directory is shared across EVERY repo a Cockpit-driven session touches, not just one.

PROMOTION REUSES agent_mine.py ENTIRELY, IT DOES NOT RE-IMPLEMENT IT:
agent_mine.py already does stage 1 of "repeated correction becomes a rule" — regex-scored
transcript scanning, Jaccard clustering by recurrence, a confirm/reject flywheel — just aimed at
agent_memory's fact store (an answer cache) instead of a binding rule set. `mine_proposals()` below
is the ONLY new code: it takes agent_mine.cluster() output and lands it as `status=proposed`
registry entries instead of duplicating the marker regexes, the clustering, or the scoring.

DOMAIN IS NOT AUTO-CLASSIFIED, AND THAT'S DELIBERATE:
Mined text has no reliable signal for "is this about design, hierarchy, communication, or process"
— a keyword heuristic here would be exactly the kind of confident-but-wrong labeling this repo's
own standing rules forbid. Proposals land with domain=None; a human sets it on approval, which is
what the approval step is FOR.

    python3 unifyd/registry.py --list
    python3 unifyd/registry.py --mine --min 3       # scan transcripts, create new proposals
    python3 unifyd/registry.py --approve <id> --domain process
"""
import argparse
import hashlib
import json
import os
import re
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

REGISTRY_DIR = os.path.expanduser("~/.claude/registry")
RULES_DIR = os.path.expanduser("~/.claude/rules")
RULE_PREFIX = "hoodie-registry-"      # so sync never touches a rule file this module didn't write

DOMAINS = ("design", "hierarchy", "communication", "process")
SCOPES = ("global", "project-overridable")
STATUSES = ("proposed", "law", "rejected", "retired")
# proposed -> law | rejected ; law -> retired ; retired -> law (reinstated); rejected is terminal.
# Not a strict forward-only ladder like tickets — a retired rule can legitimately come back — but
# every transition is still named and timestamped in status_history for the same audit reason.
_ALLOWED_TRANSITIONS = {
    "proposed": {"law", "rejected"},
    "law": {"retired"},
    "retired": {"law"},
    "rejected": set(),
}


def _now_ms():
    return int(time.time() * 1000)


def _atomic_write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(text)
    os.replace(tmp, path)


def _epath(eid, registry_dir=None):
    return os.path.join(registry_dir or REGISTRY_DIR, "%s.md" % eid)


# ── frontmatter — hand-rolled, deliberately not a YAML dependency ──────────────────────────────────
# This repo is stdlib-only by convention (unifyd/README.md, every module's own docstring). The
# frontmatter here is flat key:value pairs, one per line, which is all this record needs — pulling in
# PyYAML for five scalar fields would be the wrong trade.
_FM_LINE = re.compile(r"^([a-zA-Z_]+):\s*(.*)$")


def _render(rec):
    fm = ["---"]
    for k in ("id", "domain", "scope", "status", "provenance", "created", "updated"):
        v = rec.get(k)
        fm.append("%s: %s" % (k, "" if v is None else v))
    fm.append("status_history: %s" % json.dumps(rec.get("status_history") or []))
    fm.append("---")
    return "\n".join(fm) + "\n\n" + (rec.get("rule_text") or "").strip() + "\n"


def _parse(text):
    if not text.startswith("---"):
        return None
    parts = text.split("---", 2)
    if len(parts) < 3:
        return None
    fm_block, body = parts[1], parts[2]
    rec = dict(rule_text=body.strip())
    for line in fm_block.strip().splitlines():
        m = _FM_LINE.match(line)
        if not m:
            continue
        k, v = m.group(1), m.group(2).strip()
        if k == "status_history":
            try:
                rec[k] = json.loads(v) if v else []
            except Exception:
                rec[k] = []
        elif k in ("created", "updated"):
            try:
                rec[k] = int(v) if v else None
            except ValueError:
                rec[k] = None
        else:
            rec[k] = v or None
    return rec


def _save(rec, registry_dir=None):
    _atomic_write(_epath(rec["id"], registry_dir), _render(rec))


def get_entry(eid, registry_dir=None):
    try:
        with open(_epath(eid, registry_dir), encoding="utf-8") as fh:
            return _parse(fh.read())
    except Exception:
        return None


def list_entries(domain=None, status=None, registry_dir=None):
    d = registry_dir or REGISTRY_DIR
    out = []
    if os.path.isdir(d):
        for fn in sorted(os.listdir(d)):
            if not fn.endswith(".md"):
                continue
            rec = get_entry(fn[:-3], registry_dir=d)
            if rec:
                out.append(rec)
    if domain:
        out = [r for r in out if r.get("domain") == domain]
    if status:
        out = [r for r in out if r.get("status") == status]
    return sorted(out, key=lambda r: -(r.get("updated") or 0))


def create_entry(rule_text, domain=None, scope="global", status="proposed", provenance=None,
                 registry_dir=None):
    if domain is not None and domain not in DOMAINS:
        domain = None
    if scope not in SCOPES:
        scope = "global"
    if status not in STATUSES:
        status = "proposed"
    now = _now_ms()
    eid = "reg:" + hashlib.sha256(("%s%r" % (time.time(), rule_text)).encode()).hexdigest()[:12]
    rec = dict(id=eid, domain=domain, scope=scope, status=status, provenance=provenance,
              rule_text=rule_text, created=now, updated=now,
              status_history=[dict(status=status, at=now)])
    _save(rec, registry_dir)
    return rec


def edit_entry(eid, rule_text=None, domain=None, scope=None, provenance=None, registry_dir=None):
    rec = get_entry(eid, registry_dir)
    if not rec:
        return False
    if rule_text is not None:
        rec["rule_text"] = rule_text
    if domain is not None:
        rec["domain"] = domain if domain in DOMAINS else rec.get("domain")
    if scope is not None and scope in SCOPES:
        rec["scope"] = scope
    if provenance is not None:
        rec["provenance"] = provenance
    rec["updated"] = _now_ms()
    _save(rec, registry_dir)
    return True


def set_status(eid, new_status, registry_dir=None):
    """Named transitions, timestamped in status_history — same audit-trail reasoning as tickets'
    forward-only ladder, but the allowed graph here isn't linear (see _ALLOWED_TRANSITIONS): a
    retired rule can legitimately come back into force."""
    rec = get_entry(eid, registry_dir)
    if not rec:
        return dict(ok=False, error="not found")
    new_status = (new_status or "").strip().lower()
    if new_status not in STATUSES:
        return dict(ok=False, error="status must be one of: %s" % ", ".join(STATUSES))
    cur = rec.get("status") or "proposed"
    if new_status not in _ALLOWED_TRANSITIONS.get(cur, set()):
        return dict(ok=False, error="can't move a registry entry %s -> %s" % (cur, new_status))
    rec["status"] = new_status
    rec.setdefault("status_history", []).append(dict(status=new_status, at=_now_ms()))
    rec["updated"] = _now_ms()
    _save(rec, registry_dir)
    return dict(ok=True, status=new_status, status_history=rec["status_history"])


def approve_entry(eid, domain=None, scope=None, registry_dir=None, rules_dir=None):
    """proposed -> law, in one call — the approval step is also where a human sets the domain a
    mined proposal couldn't classify itself, per this module's own docstring on that."""
    if domain is not None or scope is not None:
        edit_entry(eid, domain=domain, scope=scope, registry_dir=registry_dir)
    res = set_status(eid, "law", registry_dir=registry_dir)
    if res.get("ok"):
        sync_rules_dir(registry_dir=registry_dir, rules_dir=rules_dir)
    return res


def reject_entry(eid, registry_dir=None):
    return set_status(eid, "rejected", registry_dir=registry_dir)


def retire_entry(eid, registry_dir=None, rules_dir=None):
    res = set_status(eid, "retired", registry_dir=registry_dir)
    if res.get("ok"):
        sync_rules_dir(registry_dir=registry_dir, rules_dir=rules_dir)
    return res


def reinstate_entry(eid, registry_dir=None, rules_dir=None):
    res = set_status(eid, "law", registry_dir=registry_dir)
    if res.get("ok"):
        sync_rules_dir(registry_dir=registry_dir, rules_dir=rules_dir)
    return res


# ── sync: registry (source of truth) -> ~/.claude/rules/ (what Claude Code actually reads) ─────────
def _rule_path(eid, rules_dir=None):
    return os.path.join(rules_dir or RULES_DIR, "%s%s.md" % (RULE_PREFIX, eid.split(":", 1)[-1]))


def sync_rules_dir(registry_dir=None, rules_dir=None):
    """Regenerate every hoodie-registry-*.md rule file from the CURRENT set of status=law entries.
    Idempotent, full-rewrite: deletes any hoodie-registry-*.md whose entry is no longer law (or gone
    entirely), writes/overwrites one for every entry that is. Only ever touches files under its own
    RULE_PREFIX — never another tool's rules file in the same directory."""
    rd = rules_dir or RULES_DIR
    law = {r["id"]: r for r in list_entries(status="law", registry_dir=registry_dir)}
    wanted = {_rule_path(eid, rd) for eid in law}
    if os.path.isdir(rd):
        for fn in os.listdir(rd):
            if not fn.startswith(RULE_PREFIX):
                continue
            p = os.path.join(rd, fn)
            if p not in wanted:
                try:
                    os.remove(p)
                except Exception:
                    pass
    written = 0
    for eid, rec in law.items():
        body = (rec.get("rule_text") or "").strip()
        header = "<!-- generated by unifyd/registry.py from %s — edit the registry entry, not this file -->\n" % eid
        _atomic_write(_rule_path(eid, rd), header + body + "\n")
        written += 1
    return dict(law=len(law), written=written, dir=rd)


# ── promotion: bridge agent_mine.py's clusters into proposed registry entries ──────────────────────
def mine_proposals(min_count=3, min_score=4, limit_files=None, registry_dir=None, root=None):
    """Run agent_mine's existing scan/cluster engine and land clusters that recur >= min_count as
    status=proposed registry entries — the ONLY new logic here is the landing, not the mining.
    Dedupes against clusters already proposed in a prior run via the cluster's own `key` (stored in
    `provenance` as `cluster:<key>`), so re-running this doesn't spam duplicate proposals for a rule
    someone hasn't reviewed yet — or already rejected. `root` overrides agent_mine's transcript
    directory (default ~/.claude/projects) — tests point this at a synthetic fixture."""
    import agent_mine as mine
    res = mine.scan(root=root, min_score=min_score, limit_files=limit_files)
    # The cluster key is the FIRST field of the `cluster:<key> | seen Nx [...] | <where>` shape
    # provenance is written in below — must split on " | " to isolate it, or every re-scan's
    # trailing "seen Nx"/where metadata (which legitimately changes run to run) gets folded into
    # the dedup key too, so nothing ever matches and every re-scan spammed a fresh duplicate
    # proposal for the same still-pending cluster. Caught by mine_proposals()'s own re-run test.
    existing_keys = {
        (r.get("provenance") or "")[len("cluster:"):].split(" | ", 1)[0]
        for r in list_entries(registry_dir=registry_dir)
        if (r.get("provenance") or "").startswith("cluster:")
    }
    created = []
    for c in res["clusters"]:
        if c["count"] < min_count or c["key"] in existing_keys:
            continue
        sample = c["samples"][0] if c["samples"] else ""
        where = "; ".join(c["where"][:3])
        fams = ",".join(sorted(c["families"]))
        provenance = "cluster:%s | seen %dx [%s] | %s" % (c["key"], c["count"], fams, where)
        rec = create_entry(sample, domain=None, scope="global", status="proposed",
                           provenance=provenance, registry_dir=registry_dir)
        created.append(rec)
    return dict(files=res["files"], turns_scanned=res["turns_scanned"],
               clusters_seen=len(res["clusters"]), proposals_created=len(created),
               entries=created)


def main(argv=None):
    ap = argparse.ArgumentParser(description="The Registry — standing rules across every repo.")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--domain", default=None)
    ap.add_argument("--status", default=None)
    ap.add_argument("--mine", action="store_true", help="scan transcripts, create new proposals")
    ap.add_argument("--min", type=int, default=3)
    ap.add_argument("--approve", default=None, help="entry id")
    ap.add_argument("--reject", default=None, help="entry id")
    ap.add_argument("--sync", action="store_true", help="regenerate ~/.claude/rules/ from law entries")
    a = ap.parse_args(argv)

    if a.mine:
        res = mine_proposals(min_count=a.min)
        print("scanned %d transcripts / %d turns -> %d clusters, %d new proposals"
              % (res["files"], res["turns_scanned"], res["clusters_seen"], res["proposals_created"]))
        return 0
    if a.approve:
        print(json.dumps(approve_entry(a.approve, domain=a.domain), indent=2))
        return 0
    if a.reject:
        print(json.dumps(reject_entry(a.reject), indent=2))
        return 0
    if a.sync:
        print(json.dumps(sync_rules_dir(), indent=2))
        return 0
    if a.list:
        for r in list_entries(domain=a.domain, status=a.status):
            print("  %-9s %-14s %-24s %s" % (r.get("status"), r.get("domain") or "-", r["id"],
                                              (r.get("rule_text") or "")[:80].replace("\n", " ")))
        return 0
    ap.error("nothing to do — use --list, --mine, --approve, --reject, or --sync")


if __name__ == "__main__":
    sys.exit(main())
