-- ===================================================================================
-- GENERATED by snowflake/build_snowflake_sql.py — do not edit by hand.
-- Regenerate:  python snowflake/build_snowflake_sql.py [--live]
-- Source of truth: unifyd/source_registry.py (raw) + the typed MASTER catalog in the
-- generator (canonical star). See snowflake/README.md.
-- ===================================================================================
--
-- 00_config.template.sql — one-time account setup + how to fill in the Tigris credentials.
--
-- Snowflake DDL (CREATE STAGE) does NOT accept session variables or string concatenation in its
-- URL / ENDPOINT / CREDENTIALS clauses — those must be string literals. So 02_stage.sql carries
-- ${...} placeholders (envsubst-style) instead. Fill them one of two ways:
--
--   A) envsubst (keeps secrets out of the committed file):
--        export TIGRIS_BUCKET=hoodie-warehouse TIGRIS_PREFIX=warehouse \
--               TIGRIS_ENDPOINT=fly.storage.tigris.dev \
--               TIGRIS_KEY_ID=... TIGRIS_SECRET=...
--        envsubst < sql/02_stage.sql | snowsql -a <acct> -u <user>          # then run 01,03,04,05,06
--      (the Tigris values are the AWS_* / BUCKET_NAME / WAREHOUSE_PREFIX the engine already uses —
--       see unifyd/warehouse.py; on Fly: `fly storage list` / the app secrets.)
--
--   B) edit sql/02_stage.sql inline and replace each ${...} with the literal value. Do NOT commit
--      real credentials back — 02_stage.sql is committed with placeholders on purpose.
--
-- Recommended secure alternative to inline keys: create the stage once by hand from a Snowflake
-- SECRET, or run the whole build under a role whose stage already exists. Never paste keys into a
-- shared worksheet history.

-- ── one-time account setup ───────────────────────────────────────────────────────────────────────
-- Compute to run the load with (XS is plenty for the seed; it auto-suspends):
CREATE WAREHOUSE IF NOT EXISTS UNIFYD_LOAD
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  COMMENT = 'Ephemeral compute for the Hoodie → Unifyd Snowflake load.';
USE WAREHOUSE UNIFYD_LOAD;

-- Then run, in order:  01_database → 02_stage (substituted) → 03_raw → 04_master → 05_marts → 06_validate
