-- ===================================================================================
-- GENERATED by snowflake/build_snowflake_sql.py — do not edit by hand.
-- Regenerate:  python snowflake/build_snowflake_sql.py [--live]
-- Source of truth: unifyd/source_registry.py (raw) + the typed MASTER catalog in the
-- generator (canonical star). See snowflake/README.md.
-- ===================================================================================
--
-- 01_database.sql — the database + the three schemas the build lands into.
CREATE DATABASE IF NOT EXISTS UNIFYD
  COMMENT = 'Hoodie → Unifyd master data. Seeded from the DuckDB-on-Tigris warehouse.';

CREATE SCHEMA IF NOT EXISTS UNIFYD.RAW
  COMMENT = 'Landing zone — one table per source Parquet, loaded schema-agnostically (INFER_SCHEMA).';
CREATE SCHEMA IF NOT EXISTS UNIFYD.MASTER
  COMMENT = 'The canonical star — dim_brand/product/item/sku, dim_outlet, src_<grain> feeds, signals. The seed to Unifyd.';
CREATE SCHEMA IF NOT EXISTS UNIFYD.MART
  COMMENT = 'Convenience views over the star (product/outlet full-width, coverage).';
