-- ===================================================================================
-- GENERATED by snowflake/build_snowflake_sql.py — do not edit by hand.
-- Regenerate:  python snowflake/build_snowflake_sql.py [--live]
-- Source of truth: unifyd/source_registry.py (raw) + the typed MASTER catalog in the
-- generator (canonical star). See snowflake/README.md.
-- ===================================================================================
--
-- 02_stage.sql — the Parquet file format + the stage the COPY statements read from.
USE SCHEMA UNIFYD.RAW;

CREATE FILE FORMAT IF NOT EXISTS PARQUET_FMT
  TYPE = PARQUET
  COMPRESSION = AUTO
  BINARY_AS_TEXT = FALSE          -- keep parquet BYTE_ARRAY strings as text, don't hex them
  TRIM_SPACE = FALSE
  COMMENT = 'Parquet as written by unifyd/warehouse.py (zstd/snappy, DuckDB/pyarrow).';

-- INTERNAL: Snowflake-managed. run_load.py PUTs each Parquet to @WH/<same path the COPYs use>,
-- so 03/04 are byte-identical between the two modes. NOT `CREATE OR REPLACE` — replacing an internal
-- stage DROPS every file already staged in it, which would silently discard prior uploads on a rerun.
CREATE STAGE IF NOT EXISTS WH
  FILE_FORMAT = PARQUET_FMT
  COMMENT = 'Hoodie warehouse Parquet, uploaded by run_load.py (internal stage).';
