-- ===================================================================================
-- GENERATED by snowflake/build_snowflake_sql.py — do not edit by hand.
-- Regenerate:  python snowflake/build_snowflake_sql.py [--live]
-- Source of truth: unifyd/source_registry.py (raw) + the typed MASTER catalog in the
-- generator (canonical star). See snowflake/README.md.
-- ===================================================================================

--
-- 03_raw_tables.sql — land every source Parquet into UNIFYD.RAW, schema-agnostically.
--
-- Each table is CREATEd from the Parquet's own schema (INFER_SCHEMA) and loaded with
-- MATCH_BY_COLUMN_NAME, so a scraper widening its columns needs no change here — exactly the
-- drift-tolerance the DuckDB read_parquet path has today.
--
-- REFRESH SEMANTICS (this is safe to run every morning):
--   • source catalogs  → CREATE OR REPLACE + COPY: the engine rewrites these files in place
--     (write_accumulate / overwrite), so the load is a FULL REFRESH that mirrors the current file.
--     Re-inferring re-picks-up drift; replacing first means a daily re-run can't double-load.
--   • time-series (retail_observations) → CREATE IF NOT EXISTS + append COPY: these are write-once
--     dated partition files, so COPY's load metadata skips what's already in and only the new day
--     lands. History accumulates instead of being rebuilt.
--
-- LAYOUT: this offline build assumes the v1 single-file layout (<name>.parquet), correct for every
-- named "full" source and the whole master layer. Tables migrated to the bucketed (v2) layout (big
-- accumulating catalogs) MUST be regenerated with `--live`, which emits their exact active part list
-- from the manifest — blindly loading a bucketed directory would double-load superseded parts.

USE SCHEMA UNIFYD.RAW;


-- ── time-series fact partitions (load the whole prefix; union_by_name) ──

-- ── source catalogs ──

-- abc_catalog   [FULL — priority seed]
--   ABC FW&S — BigCommerce catalog (UPC)
--   registry source(s): abc-catalog, abc-fws
CREATE OR REPLACE TABLE UNIFYD.RAW.ABC_CATALOG
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/abc_catalog.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.ABC_CATALOG
  FROM '@WH/abc_catalog.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  FORCE = TRUE
  ON_ERROR = ABORT_STATEMENT;


-- abc_products   [FULL — priority seed]
--   ABC FW&S — inventory + SearchSpring facets (varietal/region/type)
--   registry source(s): abc-facets
CREATE OR REPLACE TABLE UNIFYD.RAW.ABC_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/abc_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.ABC_PRODUCTS
  FROM '@WH/abc_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  FORCE = TRUE
  ON_ERROR = ABORT_STATEMENT;


-- source_taxonomy   [FULL — priority seed]
--   ABC FW&S — retailer drill-path taxonomy
--   registry source(s): abc-facets
CREATE OR REPLACE TABLE UNIFYD.RAW.SOURCE_TAXONOMY
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/source_taxonomy.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.SOURCE_TAXONOMY
  FROM '@WH/source_taxonomy.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  FORCE = TRUE
  ON_ERROR = ABORT_STATEMENT;
