-- ===================================================================================
-- GENERATED by snowflake/build_snowflake_sql.py — do not edit by hand.
-- Regenerate:  python snowflake/build_snowflake_sql.py [--live]
-- Source of truth: unifyd/source_registry.py (raw) + the typed MASTER catalog in the
-- generator (canonical star). See snowflake/README.md.
-- ===================================================================================

--
-- 03_raw_tables.sql — land every source Parquet into UNIFYD.RAW, schema-agnostically.
--
-- Each table is CREATEd from the Parquet's own schema (INFER_SCHEMA) and loaded with
-- MATCH_BY_COLUMN_NAME, so a scraper widening its columns needs no change here — exactly the
-- drift-tolerance the DuckDB read_parquet path has today. Re-running COPY is safe: Snowflake skips
-- files already loaded (load metadata) unless FORCE=TRUE.
--
-- LAYOUT: this offline build assumes the v1 single-file layout (<name>.parquet), correct for every
-- named "full" source and the whole master layer. Tables migrated to the bucketed (v2) layout (big
-- accumulating catalogs) MUST be regenerated with `--live`, which emits their exact active part list
-- from the manifest — blindly loading a bucketed directory would double-load superseded parts.

USE SCHEMA UNIFYD.RAW;


-- ── time-series fact partitions (load the whole prefix; union_by_name) ──

-- retail_observations
--   Dated per-store price + inventory observations (the fact spine; union_by_name)
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.RETAIL_OBSERVATIONS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/retail_observations/', FILE_FORMAT => 'PARQUET_FMT',
                            IGNORE_CASE => TRUE)));
COPY INTO UNIFYD.RAW.RETAIL_OBSERVATIONS
  FROM '@WH/retail_observations/'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  PATTERN = '.*[.]parquet'
  ON_ERROR = CONTINUE;


-- ── source catalogs ──

-- ab_outlets   [FULL — priority seed]
--   AB InBev — national retailer locator (where their beer is sold)
--   registry source(s): ab-inbev
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.AB_OUTLETS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/ab_outlets.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.AB_OUTLETS
  FROM '@WH/ab_outlets.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- abc_catalog   [FULL — priority seed]
--   ABC FW&S — BigCommerce catalog (UPC)
--   registry source(s): abc-catalog
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.ABC_CATALOG
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/abc_catalog.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.ABC_CATALOG
  FROM '@WH/abc_catalog.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- abc_products   [FULL — priority seed]
--   ABC FW&S — inventory + SearchSpring facets (varietal/region/type)
--   registry source(s): abc-facets, abc-fws
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.ABC_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/abc_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.ABC_PRODUCTS
  FROM '@WH/abc_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- kroger_atlas_products   [FULL — priority seed]
--   Kroger — per-store on-hand + dims + ABV (internal atlas)
--   registry source(s): kroger
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.KROGER_ATLAS_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/kroger_atlas_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.KROGER_ATLAS_PRODUCTS
  FROM '@WH/kroger_atlas_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- kroger_products   [FULL — priority seed]
--   Kroger — public API product/UPC seed (atlas GTIN universe)
--   registry source(s): kroger-api
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.KROGER_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/kroger_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.KROGER_PRODUCTS
  FROM '@WH/kroger_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- source_taxonomy   [FULL — priority seed]
--   ABC FW&S — retailer drill-path taxonomy
--   registry source(s): abc-facets
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.SOURCE_TAXONOMY
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/source_taxonomy.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.SOURCE_TAXONOMY
  FROM '@WH/source_taxonomy.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- total_wine_products   [FULL — priority seed]
--   Total Wine — full catalog (PerimeterX browser crawl)
--   registry source(s): total-wine
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.TOTAL_WINE_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/total_wine_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.TOTAL_WINE_PRODUCTS
  FROM '@WH/total_wine_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- vtinfo_titos   [FULL — priority seed]
--   Tito's — where-to-buy outlet locator
--   registry source(s): vtinfo
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.VTINFO_TITOS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/vtinfo_titos.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.VTINFO_TITOS
  FROM '@WH/vtinfo_titos.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- bbg_products
--   Salsify API
--   registry source(s): bbg
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.BBG_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/bbg_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.BBG_PRODUCTS
  FROM '@WH/bbg_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- binnys_products
--   Algolia feed
--   registry source(s): binnys
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.BINNYS_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/binnys_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.BINNYS_PRODUCTS
  FROM '@WH/binnys_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- bottlecapps_products
--   DataDome — patchright
--   registry source(s): bottlecapps
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.BOTTLECAPPS_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/bottlecapps_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.BOTTLECAPPS_PRODUCTS
  FROM '@WH/bottlecapps_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- ca_outlets
--   WAF — browser headers
--   registry source(s): ca-abc
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.CA_OUTLETS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/ca_outlets.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.CA_OUTLETS
  FROM '@WH/ca_outlets.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- census_reference
--   Census API (census_ref.build) — free key, re-derivable
--   registry source(s): census
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.CENSUS_REFERENCE
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/census_reference.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.CENSUS_REFERENCE
  FROM '@WH/census_reference.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- cityhive_products
--   Cloudflare — patchright
--   registry source(s): cityhive
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.CITYHIVE_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/cityhive_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.CITYHIVE_PRODUCTS
  FROM '@WH/cityhive_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- geocode_cache
--   Address → lat/lng/county_fips cache (persistent)
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.GEOCODE_CACHE
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/geocode_cache.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.GEOCODE_CACHE
  FROM '@WH/geocode_cache.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- haskells_products
--   first-party site; full-catalog crawl outgrew the 5400s default (timed out 07-18)
--   registry source(s): haskells
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.HASKELLS_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/haskells_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.HASKELLS_PRODUCTS
  FROM '@WH/haskells_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- hemp_inventory
--   per-store COUNTS from Shopify hemp retailers (cart-add trick) — distinct from hemp-scan listings
--   registry source(s): hemp-inventory
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.HEMP_INVENTORY
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/hemp_inventory.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.HEMP_INVENTORY
  FROM '@WH/hemp_inventory.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- hemp_products
--   hemp-bev feed
--   registry source(s): hemp-scan
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.HEMP_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/hemp_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.HEMP_PRODUCTS
  FROM '@WH/hemp_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- hemp_retailers
--   retailer discovery
--   registry source(s): hemp-finder
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.HEMP_RETAILERS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/hemp_retailers.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.HEMP_RETAILERS
  FROM '@WH/hemp_retailers.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- mont_sales
--   per-state fetchers
--   registry source(s): control-states
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.MONT_SALES
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/mont_sales.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.MONT_SALES
  FROM '@WH/mont_sales.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- naop_accounts
--   DoorDash menus
--   registry source(s): naop
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.NAOP_ACCOUNTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/naop_accounts.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.NAOP_ACCOUNTS
  FROM '@WH/naop_accounts.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- naop_beverages
--   DoorDash menus
--   registry source(s): naop
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.NAOP_BEVERAGES
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/naop_beverages.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.NAOP_BEVERAGES
  FROM '@WH/naop_beverages.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- offprem_products
--   22 markets, no-BD
--   registry source(s): offprem-census
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.OFFPREM_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/offprem_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.OFFPREM_PRODUCTS
  FROM '@WH/offprem_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- or_pricing
--   per-state fetchers
--   registry source(s): control-states
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.OR_PRICING
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/or_pricing.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.OR_PRICING
  FROM '@WH/or_pricing.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- postmates_products
--   Uber BFF, all stores
--   registry source(s): postmates
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.POSTMATES_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/postmates_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.POSTMATES_PRODUCTS
  FROM '@WH/postmates_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- postmates_stores
--   Postmates — geocoded delivery merchants (from ue_crawl)
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.POSTMATES_STORES
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/postmates_stores.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.POSTMATES_STORES
  FROM '@WH/postmates_stores.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- publix_products
--   weekly-ad API
--   registry source(s): publix
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.PUBLIX_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/publix_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.PUBLIX_PRODUCTS
  FROM '@WH/publix_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- sevennow_products
--   Incapsula — patchright
--   registry source(s): sevennow
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.SEVENNOW_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/sevennow_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.SEVENNOW_PRODUCTS
  FROM '@WH/sevennow_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- specs_products
--   Next.js sitemap
--   registry source(s): specs
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.SPECS_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/specs_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.SPECS_PRODUCTS
  FROM '@WH/specs_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- stop_and_shop_products
--   needs a warmed cookie — not headless
--   registry source(s): stop-and-shop
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.STOP_AND_SHOP_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/stop_and_shop_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.STOP_AND_SHOP_PRODUCTS
  FROM '@WH/stop_and_shop_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- target_products
--   RedSky API
--   registry source(s): target
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.TARGET_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/target_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.TARGET_PRODUCTS
  FROM '@WH/target_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- target_stores
--   RedSky API
--   registry source(s): target
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.TARGET_STORES
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/target_stores.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.TARGET_STORES
  FROM '@WH/target_stores.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- ttb_master
--   huge backfill — refresh deliberately
--   registry source(s): ttb
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.TTB_MASTER
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/ttb_master.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.TTB_MASTER
  FROM '@WH/ttb_master.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- ubereats_products
--   Uber BFF, all stores
--   registry source(s): ubereats
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.UBEREATS_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/ubereats_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.UBEREATS_PRODUCTS
  FROM '@WH/ubereats_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- ubereats_stores
--   Uber Eats — geocoded delivery merchants (from ue_crawl)
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.UBEREATS_STORES
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/ubereats_stores.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.UBEREATS_STORES
  FROM '@WH/ubereats_stores.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- ut_pricing
--   per-state fetchers
--   registry source(s): control-states
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.UT_PRICING
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/ut_pricing.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.UT_PRICING
  FROM '@WH/ut_pricing.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- walmart_products
--   __NEXT_DATA__ over stdlib HTTP, no BD — needs a warmed PX cookie
--   registry source(s): walmart
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.WALMART_PRODUCTS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/walmart_products.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.WALMART_PRODUCTS
  FROM '@WH/walmart_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- winebow_brands
--   portfolio
--   registry source(s): winebow
CREATE TABLE IF NOT EXISTS UNIFYD.RAW.WINEBOW_BRANDS
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(LOCATION => '@WH/winebow_brands.parquet', FILE_FORMAT => 'PARQUET_FMT')));
COPY INTO UNIFYD.RAW.WINEBOW_BRANDS
  FROM '@WH/winebow_brands.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;
