-- ===================================================================================
-- GENERATED by snowflake/build_snowflake_sql.py — do not edit by hand.
-- Regenerate:  python snowflake/build_snowflake_sql.py [--live]
-- Source of truth: unifyd/source_registry.py (raw) + the typed MASTER catalog in the
-- generator (canonical star). See snowflake/README.md.
-- ===================================================================================

--
-- 04_master.sql — the canonical star, typed. THE SEED TO UNIFYD.
--
-- These columns mirror the exact output of the engine's builders (build_product_master.py /
-- normalize.py / dim_outlet.py). Unlike RAW, these are stable contracts, so the DDL is explicit —
-- real types, clustering keys that mirror the query grain. Loaded from the SAME Tigris stage.
--
-- Order matters only for readability; there are no enforced FKs (Snowflake doesn't enforce them),
-- but the *_key columns join the star: dim_sku.item_key → dim_item.item_key → dim_product.product_key
-- → dim_brand.brand_key; xwalk_source_sku bridges raw source rows to those keys.
-- (--live is change-aware: a dim whose Parquet hasn't moved since the last load is left in place.)
USE SCHEMA UNIFYD.MASTER;


-- dim_brand
--   Brand grain — the top of the product hierarchy. Quality gate: a source row needs a brand to be promoted into the master.
CREATE OR REPLACE TABLE UNIFYD.MASTER.DIM_BRAND (
  brand_key         STRING,
  brand             STRING,
  brand_group       STRING,
  source_rows       NUMBER(38,0),
  sources           NUMBER(38,0),
  source_list       ARRAY,
  master_created_at NUMBER(38,0),
  master_updated_at NUMBER(38,0),
  updated_by        STRING
)
  CLUSTER BY (brand_key)
  COMMENT = 'Brand grain — the top of the product hierarchy. Quality gate: a source row needs a brand to be promoted into the master.';
COPY INTO UNIFYD.MASTER.DIM_BRAND
  FROM '@UNIFYD.RAW.WH/dim_brand.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- dim_product
--   Product grain — brand + class/type + distinguisher core. Key aligns TTB and retail spellings of the same product.
CREATE OR REPLACE TABLE UNIFYD.MASTER.DIM_PRODUCT (
  product_key       STRING,
  brand_key         STRING,
  product_name      STRING,
  core_name         STRING,
  class_type        STRING,
  flavor            STRING,
  abv               FLOAT,
  style             STRING,
  category          STRING,
  origin            STRING,
  bottled_in        STRING,
  region            STRING,
  sub_region        STRING,
  appellation       STRING,
  varietal          STRING,
  country           STRING,
  state             STRING,
  image             STRING,
  taste             STRING,
  body              STRING,
  food_pairing      STRING,
  expert_rating     STRING,
  finish            STRING,
  source_rows       NUMBER(38,0),
  sources           NUMBER(38,0),
  source_list       ARRAY,
  master_created_at NUMBER(38,0),
  master_updated_at NUMBER(38,0),
  updated_by        STRING
)
  CLUSTER BY (brand_key)
  COMMENT = 'Product grain — brand + class/type + distinguisher core. Key aligns TTB and retail spellings of the same product.';
COPY INTO UNIFYD.MASTER.DIM_PRODUCT
  FROM '@UNIFYD.RAW.WH/dim_product.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- dim_item
--   Item grain — product + size + container.
CREATE OR REPLACE TABLE UNIFYD.MASTER.DIM_ITEM (
  item_key          STRING,
  product_key       STRING,
  size_ml           FLOAT,
  packsize          STRING,
  container         STRING,
  source_rows       NUMBER(38,0),
  sources           NUMBER(38,0),
  source_list       ARRAY,
  master_created_at NUMBER(38,0),
  master_updated_at NUMBER(38,0),
  updated_by        STRING
)
  CLUSTER BY (product_key)
  COMMENT = 'Item grain — product + size + container.';
COPY INTO UNIFYD.MASTER.DIM_ITEM
  FROM '@UNIFYD.RAW.WH/dim_item.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- dim_sku
--   SKU grain — the fully-specified sellable unit (item + pack + UPC). A UPC is its global identity; vintage/edition are attributes, not splits.
CREATE OR REPLACE TABLE UNIFYD.MASTER.DIM_SKU (
  sku_key           STRING,
  item_key          STRING,
  pack              FLOAT,
  upc               STRING,
  gtin              STRING,
  vintage           STRING,
  edition           STRING,
  source_rows       NUMBER(38,0),
  sources           NUMBER(38,0),
  source_list       ARRAY,
  master_created_at NUMBER(38,0),
  master_updated_at NUMBER(38,0),
  updated_by        STRING
)
  CLUSTER BY (item_key)
  COMMENT = 'SKU grain — the fully-specified sellable unit (item + pack + UPC). A UPC is its global identity; vintage/edition are attributes, not splits.';
COPY INTO UNIFYD.MASTER.DIM_SKU
  FROM '@UNIFYD.RAW.WH/dim_sku.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- dim_supplier
--   Brand↔supplier association (SCD) with active/inactive dates — persists items across acquisition. Not a hierarchy level.
CREATE OR REPLACE TABLE UNIFYD.MASTER.DIM_SUPPLIER (
  brand_key     STRING,
  supplier_name STRING,
  active_date   NUMBER(38,0),
  inactive_date NUMBER(38,0),
  source_rows   NUMBER(38,0),
  source_list   ARRAY
)
  CLUSTER BY (brand_key)
  COMMENT = 'Brand↔supplier association (SCD) with active/inactive dates — persists items across acquisition. Not a hierarchy level.';
COPY INTO UNIFYD.MASTER.DIM_SUPPLIER
  FROM '@UNIFYD.RAW.WH/dim_supplier.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- dim_vintage
--   SKU↔vintage association — vintages do NOT multiply SKUs; tracked here so 2020 vs 2021 is queryable.
CREATE OR REPLACE TABLE UNIFYD.MASTER.DIM_VINTAGE (
  sku_key     STRING,
  vintage     STRING,
  active_date NUMBER(38,0),
  source_rows NUMBER(38,0),
  source_list ARRAY
)
  CLUSTER BY (sku_key)
  COMMENT = 'SKU↔vintage association — vintages do NOT multiply SKUs; tracked here so 2020 vs 2021 is queryable.';
COPY INTO UNIFYD.MASTER.DIM_VINTAGE
  FROM '@UNIFYD.RAW.WH/dim_vintage.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- dim_outlet
--   Distinct real outlets — the raw src_outlets book consolidated by address/phone/geo. hoodie_outlet_id is our own spine id; vpid (AB InBev/VTInfo) is a cross-ref attribute, NEVER the anchor.
CREATE OR REPLACE TABLE UNIFYD.MASTER.DIM_OUTLET (
  hoodie_outlet_id STRING,
  outlet_name      STRING,
  address          STRING,
  city             STRING,
  state            STRING,
  zip              STRING,
  lat              FLOAT,
  lng              FLOAT,
  county_fips      STRING,
  phone            STRING,
  chain            STRING,
  is_chain         BOOLEAN,
  f_beer           BOOLEAN,
  f_wine           BOOLEAN,
  f_spirits        BOOLEAN,
  f_hemp           BOOLEAN,
  f_cannabis       BOOLEAN,
  f_rtd_spirits    BOOLEAN,
  sources          ARRAY,
  source_count     NUMBER(38,0),
  record_count     NUMBER(38,0),
  vpid             STRING
)
  CLUSTER BY (state, chain)
  COMMENT = 'Distinct real outlets — the raw src_outlets book consolidated by address/phone/geo. hoodie_outlet_id is our own spine id; vpid (AB InBev/VTInfo) is a cross-ref attribute, NEVER the anchor.';
COPY INTO UNIFYD.MASTER.DIM_OUTLET
  FROM '@UNIFYD.RAW.WH/dim_outlet.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- src_brands
--   Per-source brand records, tagged with the Hoodie brand mnemonic (cross-source corroboration without a SKU match).
CREATE OR REPLACE TABLE UNIFYD.MASTER.SRC_BRANDS (
  source       STRING,
  source_id    STRING,
  hoodie_brand STRING,
  brand        STRING,
  name_key     STRING
)
  CLUSTER BY (source)
  COMMENT = 'Per-source brand records, tagged with the Hoodie brand mnemonic (cross-source corroboration without a SKU match).';
COPY INTO UNIFYD.MASTER.SRC_BRANDS
  FROM '@UNIFYD.RAW.WH/src_brands.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- src_products
--   Per-source product records + derived rich attributes (proof/age/origin_class/volume tier/organic/non_alc) and the product-type dimension id.
CREATE OR REPLACE TABLE UNIFYD.MASTER.SRC_PRODUCTS (
  source          STRING,
  source_id       STRING,
  hoodie_product  STRING,
  brand           STRING,
  product_name    STRING,
  name_key        STRING,
  flavor          STRING,
  category        STRING,
  product_type_id NUMBER(38,0),
  product_type    STRING,
  class_type      STRING,
  abv             FLOAT,
  proof           FLOAT,
  varietal        STRING,
  origin          STRING,
  origin_class    STRING,
  region          STRING,
  age_years       NUMBER(38,0),
  volume_tier     STRING,
  organic         BOOLEAN,
  non_alc         BOOLEAN,
  image           STRING
)
  CLUSTER BY (source)
  COMMENT = 'Per-source product records + derived rich attributes (proof/age/origin_class/volume tier/organic/non_alc) and the product-type dimension id.';
COPY INTO UNIFYD.MASTER.SRC_PRODUCTS
  FROM '@UNIFYD.RAW.WH/src_products.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- src_items
--   Per-source item records (product + size + container).
CREATE OR REPLACE TABLE UNIFYD.MASTER.SRC_ITEMS (
  source          STRING,
  source_id       STRING,
  hoodie_item     STRING,
  brand           STRING,
  product_name    STRING,
  name_key        STRING,
  product_type_id NUMBER(38,0),
  product_type    STRING,
  size_ml         FLOAT,
  container       STRING,
  volume_tier     STRING
)
  CLUSTER BY (source)
  COMMENT = 'Per-source item records (product + size + container).';
COPY INTO UNIFYD.MASTER.SRC_ITEMS
  FROM '@UNIFYD.RAW.WH/src_items.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- src_skus
--   Per-source SKU records with the raw + GTIN-14-normalized UPC and pack shape.
CREATE OR REPLACE TABLE UNIFYD.MASTER.SRC_SKUS (
  source          STRING,
  source_id       STRING,
  upc             STRING,
  upc_norm        STRING,
  hoodie_sku      STRING,
  brand           STRING,
  product_name    STRING,
  name_key        STRING,
  product_type_id NUMBER(38,0),
  product_type    STRING,
  size_ml         FLOAT,
  container       STRING,
  pack            FLOAT,
  pack_size       NUMBER(38,0),
  pack_type       STRING
)
  CLUSTER BY (source)
  COMMENT = 'Per-source SKU records with the raw + GTIN-14-normalized UPC and pack shape.';
COPY INTO UNIFYD.MASTER.SRC_SKUS
  FROM '@UNIFYD.RAW.WH/src_skus.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- src_outlets
--   The full book of accounts — an outlet pulled through from EVERY store-bearing source, with sell-flags (license + product-carried), chain grouping, and the match keys dim_outlet consolidates on.
CREATE OR REPLACE TABLE UNIFYD.MASTER.SRC_OUTLETS (
  source           STRING,
  store_id         STRING,
  store_name       STRING,
  chain            STRING,
  is_chain         BOOLEAN,
  f_beer           BOOLEAN,
  f_wine           BOOLEAN,
  f_spirits        BOOLEAN,
  f_hemp           BOOLEAN,
  f_cannabis       BOOLEAN,
  f_rtd_spirits    BOOLEAN,
  flag_basis       STRING,
  license_conflict BOOLEAN,
  address          STRING,
  city             STRING,
  state            STRING,
  zip              STRING,
  lat              FLOAT,
  lng              FLOAT,
  phone            STRING,
  addr_valid       BOOLEAN,
  hoodie_outlet    STRING,
  name_key         STRING,
  phone_norm       STRING,
  addr_key         STRING,
  geo_cell         STRING,
  county_fips      STRING
)
  CLUSTER BY (source, state)
  COMMENT = 'The full book of accounts — an outlet pulled through from EVERY store-bearing source, with sell-flags (license + product-carried), chain grouping, and the match keys dim_outlet consolidates on.';
COPY INTO UNIFYD.MASTER.SRC_OUTLETS
  FROM '@UNIFYD.RAW.WH/src_outlets.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- dim_product_type
--   Product-type dimension (Wine/Beer/Spirits/Hemp/Cannabis).
CREATE OR REPLACE TABLE UNIFYD.MASTER.DIM_PRODUCT_TYPE (
  product_type_id NUMBER(38,0),
  product_type    STRING
)
  COMMENT = 'Product-type dimension (Wine/Beer/Spirits/Hemp/Cannabis).';
COPY INTO UNIFYD.MASTER.DIM_PRODUCT_TYPE
  FROM '@UNIFYD.RAW.WH/dim_product_type.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- src_summary
--   Per-grain corroboration rollup: records, distinct entities, and how many are seen by 2+ sources.
CREATE OR REPLACE TABLE UNIFYD.MASTER.SRC_SUMMARY (
  grain        STRING,
  "TABLE"      STRING,
  records      NUMBER(38,0),
  entities     NUMBER(38,0),
  corroborated NUMBER(38,0)
)
  COMMENT = 'Per-grain corroboration rollup: records, distinct entities, and how many are seen by 2+ sources.';
COPY INTO UNIFYD.MASTER.SRC_SUMMARY
  FROM '@UNIFYD.RAW.WH/src_summary.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- xwalk_source_sku
--   (source, source_product_id) → product_key / item_key / sku_key. Resolves UPC-less retailer observations (ABC/Binny's/Target/Total Wine) to a master product.
CREATE OR REPLACE TABLE UNIFYD.MASTER.XWALK_SOURCE_SKU (
  source      STRING,
  product_id  STRING,
  product_key STRING,
  item_key    STRING,
  sku_key     STRING
)
  CLUSTER BY (source)
  COMMENT = '(source, source_product_id) → product_key / item_key / sku_key. Resolves UPC-less retailer observations (ABC/Binny''s/Target/Total Wine) to a master product.';
COPY INTO UNIFYD.MASTER.XWALK_SOURCE_SKU
  FROM '@UNIFYD.RAW.WH/xwalk_source_sku.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- price_coherence
--   Soft cross-source unit-price agreement per product_key: price-corroborated matches + over-merge/size DQ (divergent >2x). Never a key.
CREATE OR REPLACE TABLE UNIFYD.MASTER.PRICE_COHERENCE (
  product_key        STRING,
  n_priced           NUMBER(38,0),
  n_sources          NUMBER(38,0),
  median_unit_price  FLOAT,
  min_unit_price     FLOAT,
  max_unit_price     FLOAT,
  spread_ratio       FLOAT,
  agree_within_band  NUMBER(38,0),
  price_corroborated BOOLEAN,
  divergent          BOOLEAN
)
  COMMENT = 'Soft cross-source unit-price agreement per product_key: price-corroborated matches + over-merge/size DQ (divergent >2x). Never a key.';
COPY INTO UNIFYD.MASTER.PRICE_COHERENCE
  FROM '@UNIFYD.RAW.WH/price_coherence.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- category_cluster
--   UPC-free identity via the category discriminator tree — the match path for the ~88% of rows with no barcode.
CREATE OR REPLACE TABLE UNIFYD.MASTER.CATEGORY_CLUSTER (
  category_key STRING,
  canon        STRING,
  members      NUMBER(38,0),
  n_sources    NUMBER(38,0),
  sources      STRING,
  sample_name  STRING,
  corroborated BOOLEAN
)
  COMMENT = 'UPC-free identity via the category discriminator tree — the match path for the ~88% of rows with no barcode.';
COPY INTO UNIFYD.MASTER.CATEGORY_CLUSTER
  FROM '@UNIFYD.RAW.WH/category_cluster.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- identity_cluster
--   Resolved spine identity — union-find over category clusters (price/UPC-confirmed merges). Tier 1 = commercial-corroborated master; Tier 0 = TTB-only (TTB is a contributor, not the spine).
CREATE OR REPLACE TABLE UNIFYD.MASTER.IDENTITY_CLUSTER (
  cluster_id         STRING,
  members            NUMBER(38,0),
  n_sources          NUMBER(38,0),
  commercial_sources NUMBER(38,0),
  has_ttb            BOOLEAN,
  tier               NUMBER(38,0),
  sources            STRING,
  sample_name        STRING,
  corroborated       BOOLEAN
)
  COMMENT = 'Resolved spine identity — union-find over category clusters (price/UPC-confirmed merges). Tier 1 = commercial-corroborated master; Tier 0 = TTB-only (TTB is a contributor, not the spine).';
COPY INTO UNIFYD.MASTER.IDENTITY_CLUSTER
  FROM '@UNIFYD.RAW.WH/identity_cluster.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- src_pricing
--   Dated price observations keyed (source, store, product, upc, date).
CREATE OR REPLACE TABLE UNIFYD.MASTER.SRC_PRICING (
  "DATE"     STRING,
  source     STRING,
  store_id   STRING,
  product_id STRING,
  upc        STRING,
  price      FLOAT,
  on_promo   STRING,
  promo      STRING
)
  CLUSTER BY ("DATE")
  COMMENT = 'Dated price observations keyed (source, store, product, upc, date).';
COPY INTO UNIFYD.MASTER.SRC_PRICING
  FROM '@UNIFYD.RAW.WH/src_pricing.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;


-- src_inventory
--   Dated inventory observations keyed (source, store, product, upc, date).
CREATE OR REPLACE TABLE UNIFYD.MASTER.SRC_INVENTORY (
  "DATE"      STRING,
  source      STRING,
  store_id    STRING,
  product_id  STRING,
  upc         STRING,
  qty         FLOAT,
  in_stock    STRING,
  stock_level STRING
)
  CLUSTER BY ("DATE")
  COMMENT = 'Dated inventory observations keyed (source, store, product, upc, date).';
COPY INTO UNIFYD.MASTER.SRC_INVENTORY
  FROM '@UNIFYD.RAW.WH/src_inventory.parquet'
  FILE_FORMAT = (FORMAT_NAME = 'UNIFYD.RAW.PARQUET_FMT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = ABORT_STATEMENT;
