-- ===================================================================================
-- GENERATED by snowflake/build_snowflake_sql.py — do not edit by hand.
-- Regenerate:  python snowflake/build_snowflake_sql.py [--live]
-- Source of truth: unifyd/source_registry.py (raw) + the typed MASTER catalog in the
-- generator (canonical star). See snowflake/README.md.
-- ===================================================================================
--
-- 05_marts.sql — convenience views over the star (the shapes the apps ask for).
USE SCHEMA UNIFYD.MART;

-- Full-width product: SKU joined up through item → product → brand. One row per sellable unit.
CREATE OR REPLACE VIEW v_product_full COMMENT = 'SKU × item × product × brand — the whole product line.' AS
SELECT s.sku_key, s.upc, s.gtin, s.pack, s.vintage, s.edition,
       i.item_key, i.size_ml, i.container,
       p.product_key, p.product_name, p.core_name, p.class_type, p.category, p.abv, p.varietal,
       p.origin, p.region, p.appellation, p.image,
       b.brand_key, b.brand,
       s.sources AS sku_sources, s.source_rows AS sku_source_rows
FROM UNIFYD.MASTER.dim_sku    s
LEFT JOIN UNIFYD.MASTER.dim_item    i ON i.item_key    = s.item_key
LEFT JOIN UNIFYD.MASTER.dim_product p ON p.product_key = i.product_key
LEFT JOIN UNIFYD.MASTER.dim_brand   b ON b.brand_key   = p.brand_key;

-- Outlet book with sell-flags and chain grouping — the account map.
CREATE OR REPLACE VIEW v_outlet_full COMMENT = 'Distinct outlets with sell-flags, chain, geo, corroboration.' AS
SELECT hoodie_outlet_id, outlet_name, chain, is_chain, address, city, state, zip, lat, lng,
       county_fips, phone, f_beer, f_wine, f_spirits, f_hemp, f_cannabis, f_rtd_spirits,
       source_count, sources, vpid
FROM UNIFYD.MASTER.dim_outlet;

-- Source coverage: how many distinct entities each source contributes at each grain, and how many
-- are corroborated by 2+ sources. Reads the corroboration rollup normalize.py already computes.
CREATE OR REPLACE VIEW v_source_coverage COMMENT = 'Per-grain entity + corroboration counts by source.' AS
SELECT grain, "TABLE" AS src_table, records, entities, corroborated,
       ROUND(100.0 * corroborated / NULLIF(entities, 0), 1) AS corroborated_pct
FROM UNIFYD.MASTER.src_summary;

-- Chain rollup: outlet count + sell-flag reach per chain banner (Total Wine, Kroger, ABC, …).
CREATE OR REPLACE VIEW v_chain_rollup COMMENT = 'Outlets per chain banner with sell-flag reach.' AS
SELECT COALESCE(NULLIF(chain, ''), '(independent)') AS chain,
       COUNT(*) AS outlets,
       COUNT_IF(f_beer) AS sells_beer, COUNT_IF(f_wine) AS sells_wine,
       COUNT_IF(f_spirits) AS sells_spirits, COUNT_IF(f_rtd_spirits) AS rtd_spirits_candidates
FROM UNIFYD.MASTER.dim_outlet
GROUP BY 1
ORDER BY outlets DESC;
