-- ===================================================================================
-- GENERATED by snowflake/build_snowflake_sql.py — do not edit by hand.
-- Regenerate:  python snowflake/build_snowflake_sql.py [--live]
-- Source of truth: unifyd/source_registry.py (raw) + the typed MASTER catalog in the
-- generator (canonical star). See snowflake/README.md.
-- ===================================================================================
--
-- 06_validate.sql — post-load assertions. The named "full" sources MUST be non-empty; the star must
-- have landed; the joins must resolve. Run after 03/04. Eyeball the STATUS column.

-- 0) THE HEADLINE — total records loaded + the per-table breakdown (from INFORMATION_SCHEMA.ROW_COUNT,
--    maintained by Snowflake, so this is cheap — no table scans). This is the "N sources / M records"
--    answer, refreshed every run.
SELECT TABLE_SCHEMA AS schema_name, COUNT(*) AS tables, TO_VARCHAR(SUM(ROW_COUNT), '999,999,999,999') AS records
FROM UNIFYD.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('RAW', 'MASTER') AND TABLE_TYPE = 'BASE TABLE'
GROUP BY ROLLUP (TABLE_SCHEMA)
ORDER BY schema_name NULLS LAST;

SELECT TABLE_SCHEMA AS schema_name, TABLE_NAME AS table_name, ROW_COUNT AS n_rows
FROM UNIFYD.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('RAW', 'MASTER') AND TABLE_TYPE = 'BASE TABLE'
ORDER BY ROW_COUNT DESC NULLS LAST;

-- 1) Named priority sources — every one must be > 0 rows (an EMPTY here = a failed load, not a rebuild).

WITH want AS (SELECT COLUMN1 AS table_name FROM VALUES ('TOTAL_WINE_PRODUCTS'), ('KROGER_ATLAS_PRODUCTS'), ('KROGER_PRODUCTS'), ('ABC_PRODUCTS'), ('ABC_CATALOG'), ('SOURCE_TAXONOMY'), ('AB_OUTLETS'), ('VTINFO_TITOS')),
     have AS (SELECT TABLE_NAME, ROW_COUNT FROM UNIFYD.INFORMATION_SCHEMA.TABLES
              WHERE TABLE_SCHEMA = 'RAW' AND TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME IN ('TOTAL_WINE_PRODUCTS', 'KROGER_ATLAS_PRODUCTS', 'KROGER_PRODUCTS', 'ABC_PRODUCTS', 'ABC_CATALOG', 'SOURCE_TAXONOMY', 'AB_OUTLETS', 'VTINFO_TITOS'))
SELECT w.table_name,
       COALESCE(h.ROW_COUNT, 0) AS n_rows,
       CASE WHEN h.TABLE_NAME IS NULL THEN 'MISSING — never loaded'
            WHEN COALESCE(h.ROW_COUNT, 0) = 0 THEN 'EMPTY — investigate'
            ELSE 'OK' END AS status
FROM want w LEFT JOIN have h ON h.TABLE_NAME = w.table_name
ORDER BY status, w.table_name
ORDER BY table_name;

-- 2) The canonical star landed.
SELECT 'dim_brand'   AS tbl, COUNT(*) FROM UNIFYD.MASTER.dim_brand
UNION ALL SELECT 'dim_product', COUNT(*) FROM UNIFYD.MASTER.dim_product
UNION ALL SELECT 'dim_item',    COUNT(*) FROM UNIFYD.MASTER.dim_item
UNION ALL SELECT 'dim_sku',     COUNT(*) FROM UNIFYD.MASTER.dim_sku
UNION ALL SELECT 'dim_outlet',  COUNT(*) FROM UNIFYD.MASTER.dim_outlet
UNION ALL SELECT 'xwalk_source_sku', COUNT(*) FROM UNIFYD.MASTER.xwalk_source_sku
ORDER BY tbl;

-- 3) Referential sanity — every SKU's item resolves up the hierarchy (orphans = a broken load).
SELECT COUNT(*) AS skus,
       COUNT_IF(i.item_key IS NULL) AS skus_missing_item,
       COUNT_IF(p.product_key IS NULL) AS items_missing_product
FROM UNIFYD.MASTER.dim_sku s
LEFT JOIN UNIFYD.MASTER.dim_item    i ON i.item_key    = s.item_key
LEFT JOIN UNIFYD.MASTER.dim_product p ON p.product_key = i.product_key;

-- 4) Outlet corroboration — how many of the named outlet sources made it into dim_outlet.
SELECT COUNT(*) AS distinct_outlets,
       COUNT_IF(source_count >= 2) AS corroborated_2plus,
       COUNT_IF(ARRAY_CONTAINS('ab-inbev'::VARIANT, sources)) AS from_ab_inbev,
       COUNT_IF(vpid <> '') AS with_vpid
FROM UNIFYD.MASTER.dim_outlet;
