-- ===================================================================================
-- GENERATED by snowflake/build_snowflake_sql.py — do not edit by hand.
-- Regenerate:  python snowflake/build_snowflake_sql.py [--live]
-- Source of truth: unifyd/source_registry.py (raw) + the typed MASTER catalog in the
-- generator (canonical star). See snowflake/README.md.
-- ===================================================================================
--
-- 06_validate.sql — post-load assertions. The named "full" sources MUST be non-empty; the star must
-- have landed; the joins must resolve. Run after 03/04. Eyeball the STATUS column.

-- 1) Named priority sources — every one must be > 0 rows (an EMPTY here = a failed load, not a rebuild).
SELECT 'total_wine_products' AS table_name, COUNT(*) AS n_rows, IFF(COUNT(*) > 0, 'OK', 'EMPTY — investigate') AS status FROM UNIFYD.RAW.TOTAL_WINE_PRODUCTS
UNION ALL
SELECT 'kroger_atlas_products' AS table_name, COUNT(*) AS n_rows, IFF(COUNT(*) > 0, 'OK', 'EMPTY — investigate') AS status FROM UNIFYD.RAW.KROGER_ATLAS_PRODUCTS
UNION ALL
SELECT 'kroger_products' AS table_name, COUNT(*) AS n_rows, IFF(COUNT(*) > 0, 'OK', 'EMPTY — investigate') AS status FROM UNIFYD.RAW.KROGER_PRODUCTS
UNION ALL
SELECT 'abc_products' AS table_name, COUNT(*) AS n_rows, IFF(COUNT(*) > 0, 'OK', 'EMPTY — investigate') AS status FROM UNIFYD.RAW.ABC_PRODUCTS
UNION ALL
SELECT 'abc_catalog' AS table_name, COUNT(*) AS n_rows, IFF(COUNT(*) > 0, 'OK', 'EMPTY — investigate') AS status FROM UNIFYD.RAW.ABC_CATALOG
UNION ALL
SELECT 'source_taxonomy' AS table_name, COUNT(*) AS n_rows, IFF(COUNT(*) > 0, 'OK', 'EMPTY — investigate') AS status FROM UNIFYD.RAW.SOURCE_TAXONOMY
UNION ALL
SELECT 'ab_outlets' AS table_name, COUNT(*) AS n_rows, IFF(COUNT(*) > 0, 'OK', 'EMPTY — investigate') AS status FROM UNIFYD.RAW.AB_OUTLETS
UNION ALL
SELECT 'vtinfo_titos' AS table_name, COUNT(*) AS n_rows, IFF(COUNT(*) > 0, 'OK', 'EMPTY — investigate') AS status FROM UNIFYD.RAW.VTINFO_TITOS
ORDER BY table_name;

-- 2) The canonical star landed.
SELECT 'dim_brand'   AS tbl, COUNT(*) FROM UNIFYD.MASTER.dim_brand
UNION ALL SELECT 'dim_product', COUNT(*) FROM UNIFYD.MASTER.dim_product
UNION ALL SELECT 'dim_item',    COUNT(*) FROM UNIFYD.MASTER.dim_item
UNION ALL SELECT 'dim_sku',     COUNT(*) FROM UNIFYD.MASTER.dim_sku
UNION ALL SELECT 'dim_outlet',  COUNT(*) FROM UNIFYD.MASTER.dim_outlet
UNION ALL SELECT 'xwalk_source_sku', COUNT(*) FROM UNIFYD.MASTER.xwalk_source_sku
ORDER BY tbl;

-- 3) Referential sanity — every SKU's item resolves up the hierarchy (orphans = a broken load).
SELECT COUNT(*) AS skus,
       COUNT_IF(i.item_key IS NULL) AS skus_missing_item,
       COUNT_IF(p.product_key IS NULL) AS items_missing_product
FROM UNIFYD.MASTER.dim_sku s
LEFT JOIN UNIFYD.MASTER.dim_item    i ON i.item_key    = s.item_key
LEFT JOIN UNIFYD.MASTER.dim_product p ON p.product_key = i.product_key;

-- 4) Outlet corroboration — how many of the named outlet sources made it into dim_outlet.
SELECT COUNT(*) AS distinct_outlets,
       COUNT_IF(source_count >= 2) AS corroborated_2plus,
       COUNT_IF(ARRAY_CONTAINS('ab-inbev'::VARIANT, sources)) AS from_ab_inbev,
       COUNT_IF(vpid <> '') AS with_vpid
FROM UNIFYD.MASTER.dim_outlet;
