-- ===================================================================================
-- GENERATED by snowflake/build_snowflake_sql.py — do not edit by hand.
-- Regenerate:  python snowflake/build_snowflake_sql.py [--live]
-- Source of truth: unifyd/source_registry.py (raw) + the typed MASTER catalog in the
-- generator (canonical star). See snowflake/README.md.
-- ===================================================================================
--
-- 07_grants.sql — read access for humans/BI. The loader owns every object it creates and Snowflake
-- grants nothing implicitly, so without this a successful load is unreadable in the UI.
-- Roles: SNOWFLAKE_READER_ROLES (default SYSADMIN).

GRANT USAGE  ON DATABASE UNIFYD TO ROLE SYSADMIN;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE UNIFYD TO ROLE SYSADMIN;
GRANT SELECT ON ALL TABLES  IN DATABASE UNIFYD TO ROLE SYSADMIN;
GRANT SELECT ON ALL VIEWS   IN DATABASE UNIFYD TO ROLE SYSADMIN;
GRANT USAGE  ON FUTURE SCHEMAS IN DATABASE UNIFYD TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE TABLES  IN DATABASE UNIFYD TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE VIEWS   IN DATABASE UNIFYD TO ROLE SYSADMIN;
